### ISSUE TITLE
CPU 100% and lock-up on persp-kill with my common header-line usage

### ISSUE THREAD

**Issue by codeasone** [Bad-ptr/common-header-mode-line.el#2]
First thanks for developing this Emacs extension, I've been getting a lot of value from it over the past year.

I use [perspective](https://github.com/nex3/perspective-el) and like having the list of perspectives in the header-line: 

```elisp
(setq persp-show-modestring 'header)
```

Having a common header line works great when dealing with lots of splits in my Emacs frame.

With the [recent updates](https://github.com/nex3/perspective-el/releases) to `2.x` however, `persp-kill` is failing; the common header-line remains unchanged; furthermore, if I don't `ctrl-g` on the mode-line the CPU flatlines at 100%.

Without `common-header-mode-line` enabled, `persp-kill` is working as expected.

To make this easy to reproduce, I've created an uber-minimal [dotemacs](https://github.com/codeasone/dotemacs-persp-kill) with the conflicting package versions pre-installed into the `elpa` folder:

- [common-header-mode-line-0.5.6](https://github.com/codeasone/dotemacs-persp-kill/tree/master/elpa/common-header-mode-line-0.5.6); and
- [perspective-20180614.1533](https://github.com/codeasone/dotemacs-persp-kill/tree/master/elpa/perspective-20180614.1533)

### Steps to reproduce:

1. Clone `git@github.com:codeasone/dotemacs-persp-kill.git` into `~/.emacs.d` (temporarily moving current config as required)
2. Run Emacs - I'm using `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-06-01`
3. The `[main]` perspective should appear in the common header-line
4. `M-x persp-switch` and choose a name for the new perspective e.g. `foobar`
5. `M-x persp-kill` and select `foobar` from the `minibar`

### Expected behaviour:

- The common header-line should change from `[main|foobar]` to `[main]`.

### Actual behaviour:

- The common header-line remains unchanged
- Minibar presents a frozen prompt
- CPU 100% after short period unless `persp-kill` is backed-out with `ctrl-g`

Would appreciate if anyone close the implementation details of this module could take a look.

**Comment by Bad-ptr** [comment]
The problem is here https://github.com/codeasone/dotemacs-persp-kill/blob/6034cb3ef3c2b3af9995635dbd313dbde08f8481/elpa/perspective-20180614.1533/perspective.el#L597

The while loop tries to remove the `*common-header-line*` buffer from it's window, but it can't do that, so it loops forever.

The fix is to redefine the `persp-remove-buffer`:

```elisp
(defun persp-remove-buffer (buffer)
  "Disassociate BUFFER with the current perspective.

See also `persp-switch' and `persp-add-buffer'."
  (interactive "bRemove buffer from perspective: \n")
  (setq buffer (get-buffer buffer))
  (cond ((not (buffer-live-p buffer)))
        ;; Only kill the buffer if no other perspectives are using it
        ((not (persp-buffer-in-other-p buffer))
         (kill-buffer buffer))
        ;; Make the buffer go away if we can see it.
        ((get-buffer-window buffer)
         (let ((w (get-buffer-window buffer)))
           (while w
             (with-selected-window w
               (bury-buffer))
             (let ((nw (get-buffer-window buffer)))
               (setq w (unless (eq w nw) nw))))))
        (t (bury-buffer buffer)))
  (setf (persp-buffers (persp-curr)) (remq buffer (persp-buffers (persp-curr)))))
```

**Comment by codeasone** [comment]
Ah yes, well that patch certainly seems to fix the problem for me - thank you for taking a look.

**Comment by codeasone** [comment]
@Bad-ptr do you think it's worth raising a PR on https://github.com/nex3/perspective-el with this code?

I'm happy to propose the patch on your behalf - as you prefer.

**Comment by Bad-ptr** [comment]
> do you think it's worth raising a PR on https://github.com/nex3/perspective-el with this code?

Yes, it's worth it.
